export type ButtonVariant =
  | 'primary'
  | 'outline'
  | 'ghost'
  | 'iconPrimary'
  | 'iconOutline'
  | 'iconGhost'
export type ButtonSize = 'small' | 'large'
export type ButtonType = 'button' | 'submit' | 'reset'
export type ButtonTarget = '_blank' | '_self' | '_parent' | '_top'
